title: S. M Tasnimul Hasan
description: Software Engineer, QA @ Enosis Solutions Ltd.
baseurl: "/remple/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "thsamit.cse@gmail.com"
linkedin: "https://linkedin.com/in/s-m-tasnimul-hasan-samit/"
github: "https://github.com/samithasan142"
#website: "http://tasnimul.github.io/"
#medium: "https://tasnimul.medium.com/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
